version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      - API_URL=http://localhost:8080
    image: docker.io/eruobodo/myapp:latest
